os: linux
dist: xenial
git:
  depth: 5
language: elixir
elixir: '1.11.1'
otp_release: '23.0'
cache:
  directories:
  - .mix
  - _build
  - deps
  - priv/plts

services:
- postgresql

env:
  global:
  - PGUSER=postgres
  - PGPORT=5432
  - PG_PORT=5432
  - CI=travis


before_script:
# - cp config/travis.exs config/test.exs
- psql --version
- mix deps.get
- mix compile
# - mix ecto.setup

notifications:
  email: false

jobs:
  include:
  - stage: Unit tests
    name: Elixir v1.11.1
    env:
    - MIX_ENV=test
    script: mix test
#   - stage: Credo
#     name: Elixir v1.11.1
#     env:
#     - MIX_ENV=dev
#     script: mix credo
  - stage: Compile test (warnings as errors)
    name: Elixir v1.11.1
    env:
    - MIX_ENV=dev
#   - stage: Dialyzer
#     name: Elixir v1.11.1
#     env:
#     - MIX_ENV=dev
#     script: travis_wait mix dialyzer --format short --halt-exit-status